{% set version = "0.3.1" %}

package:
  name: sincei
  version: {{ version }}

source:
  url: https://github.com/bhardwaj-lab/sincei/archive/refs/tags/{{ version }}.tar.gz
  sha256: 97c583be03a45ae1692312a147c00ca26d949755bd3b5a998c397fdd390dc86f

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage("sincei", max_pin="x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - umap-learn
    - pandas
    - deeptools
    - scanpy
    - loompy
    - gensim
    - leidenalg
    - python-igraph
    - importlib-metadata

test:
  imports:
    - sincei

  commands:
    - sincei --version

about:
  home: https://github.com/bhardwaj-lab/sincei
  license: MIT
  license_file: LICENCE.txt
  summary: A user-friendly toolkit for QC, counting, clustering and plotting of single-cell (epi)genomics data.

extra:
  identifiers:
    - biotools:sincei
    - doi:10.5281/zenodo.8105536
